kind: pipeline
type: docker
name: default

concurrency:
  limit: 1

trigger:
  branch:
    - master

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache:latest
    pull: if-not-exists
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: node:14.11
    commands:
      - npm install --prefer-offline --no-audit --progress=false
      - npm run generate

  - name: rebuild-cache
    image: drillster/drone-volume-cache:latest
    pull: if-not-exists
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: deploy
    image: drillster/drone-rsync:latest
    pull: if-not-exists
    environment:
      RSYNC_KEY:
        from_secret: bergesen_ssh_key
    settings:
      user: bergesen
      hosts:
        - banana.444.no
      source: ./dist/
      target: ~/www/bergesenstiftelsen.no/public/
      secrets: ["bergesen_ssh_key"]

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache
